services:
  abiotic-server:
    image: andrewsav/abiotic-factor
    container_name: abiotic-factor
    init: true
    restart: unless-stopped
    volumes:
      - ./gamefiles:/server
    environment:
      - MaxServerPlayers=6
      - Port=7777
      - QueryPort=27015
      - ServerPassword=password
      - SteamServerName=Linux Server
      - UsePerfThreads=true
      - NoAsyncLoadingThread=true
      - WorldSaveName=Cascade
      - AutoUpdate=true
#     - AdditionalArgs=-SandboxIniPath=Config/WindowsServer/Server1Sandbox.ini
    ports:
      - 0.0.0.0:7777:7777/udp
      - 0.0.0.0:27015:27015/udp
