services:
  abiotic-server:
    image: andrewsav/abiotic-factor
    container_name: abiotic-factor
    init: true
    restart: unless-stopped
    volumes:
      - ./server:/server
    environment:
      #SKIP_UPDATE: 1
      args: >-
        -useperfthreads
        -NoAsyncLoadingThread
        -PORT=7777
        -QUERYPORT=27015
        -ServerPassword=password
        -AdminPassword=password
        -SteamServerName=Linux Server
        -MaxServerPlayers=6
        -WorldSaveName=Cascade
        -SandboxIniPath=SaveGames/Server/Worlds/Cascade/SanboxSettings.ini
        -AdminIniPath=SaveGames/Server/Admin.ini
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
